<?php
// Automatically Generated by TestLink Installer - Mon, 07 Apr 25 22:08:39 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.1.50');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
